# Generated by Django 5.2.7 on 2025-10-16 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3)),
                ('professor', models.CharField(blank=True, max_length=100)),
                ('startperiod', models.TimeField(blank=True, null=True)),
                ('endperiod', models.TimeField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, choices=[(1, 'Thứ Hai'), (2, 'Thứ Ba'), (3, 'Thứ Tư'), (4, 'Thứ Năm'), (5, 'Thứ Sáu'), (6, 'Thứ Bảy'), (7, 'Chủ Nhật')], null=True)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('weeks', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.IntegerField()),
                ('startperiod', models.TimeField()),
                ('endperiod', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.schedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.subject')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='schedule_editor.subject'),
        ),
    ]
