# Generated by Django 5.2.7 on 2025-10-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='endperiod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='startperiod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
