# Generated by Django 5.2.7 on 2025-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_editor', '0002_alter_subject_endperiod_alter_subject_startperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
    ]
