# Generated by Django 5.2.7 on 2025-10-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_editor', '0003_scheduleitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='endperiod',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='startperiod',
            field=models.IntegerField(),
        ),
    ]
